user default off
user SESSIONS_USERNAME on >SESSIONS_PASSWORD ~refresh:* +ZADD +ZREM +ZCOUNT +ZSCORE +PING
user GC_USERNAME on >GC_PASSWORD ~refresh:* +ZREMRANGEBYSCORE +SCAN +COMMAND +PING

appendonly yes
protected-mode no
bind 0.0.0.0

maxmemory 1024MB
maxmemory-policy allkeys-lfu
save ""
