user default off
user SESSIONS_USERNAME on >SESSIONS_PASSWORD ~refresh:* +ZADD +ZREM +ZCOUNT +ZSCORE +PING +CLUSTER +INFO
user GC_USERNAME on >GC_PASSWORD ~refresh:* +ZREMRANGEBYSCORE +SCAN +COMMAND +PING +CLUSTER +INFO

cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000

appendonly no
protected-mode no
bind 0.0.0.0

maxmemory 1024MB
maxmemory-policy allkeys-lfu
save ""
