user default off
user SESSION_USER_USERNAME on >SESSION_USER_PASSWORD ~session:* +GET +SETEX +DEL +SCAN
user REFRESH_USER_USERNAME on >REFRESH_USER_PASSWORD ~refresh:* +GET +SETEX +DEL +SCAN

maxmemory 128MB
maxmemory-policy allkeys-lfu
save ""
