apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: deltabasebackend-backend:local
          envFrom:
            - secretRef:
                name: backend-secrets
            - configMapRef:
                name: backend-config-map
            - secretRef:
                name: session-store-secrets
            - configMapRef:
                name: session-store-config-map
            - secretRef:
                name: database-secrets
            - configMapRef:
                name: database-config-map
