apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: session-store
  labels:
    app: session-store
spec:
  serviceName: session-store-service
  replicas: 4
  selector:
    matchLabels:
      app: session-store
  template:
    metadata:
      name: session-store
      labels:
        app: session-store
    spec:
      containers:
        - name: redis
          image: deltabasebackend-session_store:local
          envFrom:
            - secretRef:
                name: session-store-secrets
            - configMapRef:
                name: session-store-config-map
