apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-store-deployment
  labels:
    name: session-store-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: session-store
  template:
    metadata:
      name: session-store
      labels:
        name: session-store
    spec:
      containers:
        - name: redis
          image: deltabase-session-store:local
