apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: session-store
  labels:
    app: session-store
spec:
  serviceName: session-store-service
  replicas: 4
  selector:
    matchLabels:
      app: session-store
  template:
    metadata:
      name: session-store
      labels:
        app: session-store
    spec:
      containers:
        - name: redis
          image: deltabasebackend-session_store:local
          envFrom:
            - secretRef:
                name: backend-session-store-secrets
            - configMapRef:
                name: session-store-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: session-store-service
spec:
  clusterIP: None
  selector:
    app: session-store
  ports:
    - port: 6379
      targetPort: 6379
