CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  created_at INT NOT NULL,
  password_hash BYTEA NOT NULL,
  salt BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS repos (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  private BOOLEAN NOT NULL,
  owner TEXT NOT NULL,
  created_at INT NOT NULL,
  stars INT NOT NULL
);
