apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config-map
data:
  API_VERSION: v1
  BACKEND_PORT: "5000"
  BACKEND_HOSTNAME: backend-service
  JWT_LIFESPAN: "15m"
  TOKEN_TIMEOUT: "720d"
  TOKEN_LIMIT: "10"
