apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-store-deployment
  labels:
    app: session-store-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-store
  template:
    metadata:
      name: session-store
      labels:
        app: session-store
    spec:
      containers:
        - name: redis
          image: deltabasebackend-session_store:local
          envFrom:
            - secretRef:
                name: backend-session-store-secrets
            - configMapRef:
                name: session-store-config-map
