apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXJuYW1lOnBhc3N3b3JkQGRhdGFiYXNlLXNlcnZpY2U6NTQzMi9kYg== # postgresql://username:password@database-service:5432/db
