apiVersion: v1
kind: Secret
metadata:
  name: session-store-secrets
data:
  SESSION_STORE_SESSIONS_USERNAME: c2Vzc2lvbnM= # sessions
  SESSION_STORE_SESSIONS_PASSWORD: c2Vzc2lvbnM= # sessions

  SESSION_STORE_GC_USERNAME: Z2M= # gc
  SESSION_STORE_GC_PASSWORD: Z2M= # gc
